### ISSUE TITLE
clip.removeNotes leads to MPE warning

### ISSUE THREAD

**Issue by driangle** [leolabs/ableton-js#106]
Thank you so much for your amazing work with this repo. It will open many new possibilities for projects I have in mind.

When I run the following code I get a warning from Ableton:

```
await clip?.removeNotes(0, 0, 4, 128);
```

<img width="601" alt="Screen Shot 2023-09-09 at 5 59 53 PM" src="https://github.com/leolabs/ableton-js/assets/292845/8319788f-bfda-4910-b0d2-c9b4c08c9901">

It's not a big deal, because I can "Proceed" and disable the warning, but just wanted to make you aware.

Ableton Version: `11.3.10`
ableton-js version: `3.3.2`

**Comment by leolabs** [comment]
Thanks for letting me know! I just took a look at the API docs, and it seems like you can use another command that I haven't implemented yet. Could you try using:

```ts
await clip?.sendCommand("remove_notes_extended", [
      fromTime,
      fromPitch,
      timeSpan,
      pitchSpan,
    ]);
```

Let me know if this works!

**Comment by leolabs** [comment]
I've just added this new function to ableton-js in ac022718f0b16317d8fdf70ff1c8d77eaaa0f384
