### ISSUE TITLE
Creating Scenes

### ISSUE THREAD

**Issue by josiahmaharaj** [leolabs/ableton-js#109]
I've been playing around with this repo - it's really cool!
Is it possible to create scenes with names/bpm attached? I can't seem to figure it out.

When I create a scene, it returns a String, but I cannot access that specific scene or perform any actions on it...like set name or tempo.

Would appreciate any help, thanks!

**Comment by leolabs** [comment]
Hey @josiahmaharaj, you're right, that shouldn't happen!

I just published an updated version that properly returns the created scene, so you can use the following to create a scene with a given name and tempo:

```ts
const scene = await ableton.song.createScene();
await scene.set("name", "Test");
await scene.set("tempo", 130);
```

Let me know if this works for you!

**Comment by josiahmaharaj** [comment]
Fantastic @leolabs!
Works great.

Thanks for the response and help.
