### ISSUE TITLE
Can't "fire" a Clip to start playing

### ISSUE THREAD

**Issue by johnlindquist** [leolabs/ableton-js#11]
Goal: Trigger the first clip of the first track to start playing

Attempt:
```javascript
    let tracks = await ableton.song.get("tracks")
    let firstTrack = tracks[0]

    let clipSlot = await firstTrack.get("clip_slots")
    let firstClipSlot = clipSlot[0]
    
    await firstClipSlot.sendCommand("fire")
```

Error:

```bash
UnhandledPromiseRejectionWarning: Error: The command clip_slot(10074456552).fire(undefined) timed out after 2000 ms.
```

From everything I've read, the command name should be `"fire"` with only optional parameters.
![callclipfire.png](https://cdn-resources.ableton.com/resources/2013/06/17/callclipfire.png)

Am I missing something? I don't know what else to try...

**Comment by leolabs** [comment]
Hey @johnlindquist,

Thanks for your bug report! I haven't had the time to implement the ClipSlot methods yet but will do so this weekend. The `sendCommand` method is internal and while it would theoretically work, the Python-side of the project doesn't support the "fire" command yet :)

**Comment by johnlindquist** [comment]
Awesome, thanks!

**Comment by johnlindquist** [comment]
Do you think this would be pretty simple to implement if I were to try myself? Is it just adding a method to the ClipSlots.py?

**Comment by leolabs** [comment]
Ah, shoot. I didn't have time to work on this yet. If you're willing to invest some time, that'd be awesome! :)

Implementing the function shouldn't be too hard. You can have a look at the Track namespace, for example, and how the functions are implemented there – both on the Python part and on the JS part.

If you use macOS, you can use the scripts stored in the package.json to automatically load the Python scripts into Ableton, which saves some time when you're working on the library.

Please let me know if you have any more questions :)
