### ISSUE TITLE
[OFFTOP] how to use "output_meter_left" or any data for visualize 

### ISSUE THREAD

**Issue by wdoer** [leolabs/ableton-js#121]
hi, thank you for this solution!!, is a very better for me)

please tell me if u know, how i can use "output_meter_left" data for visualize, im trying make self algorithm but attempt be fail, sorry for offtop, but i idk where i can ask this question, thanks for any reply!!!

**Comment by leolabs** [comment]
That depends on what software you'd like to use to visualize the values. You could use ableton-js to subscribe to value changes and send those to something like Max, TouchDesigner, or Resolume using [OSC](https://www.npmjs.com/package/node-osc) to create visuals for them.

**Comment by wdoer** [comment]
> That depends on what software you'd like to use to visualize the values. You could use ableton-js to subscribe to value changes and send those to something like Max, TouchDesigner, or Resolume using [OSC](https://www.npmjs.com/package/node-osc) to create visuals for them.

thanks for the reply! I just use simple js, I have a video that needs to be animated based on variables that are available in ableton-js, unfortunately I don't see the possibility of using third-party solutions, as they only complicate the chain of actions (

**Comment by leolabs** [comment]
Unfortunately, I don't have enough knowledge of programmatic video manipulation to help you with this. Maybe someone else can chime in with ideas on how to approach this?

**Comment by wdoer** [comment]
closing this topic because it not relevance of this theme
