### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tobiasger** [leolabs/ableton-js#18]
Sorry for a beginner question, but I'm not familiar with TypeScript and I feel that the process for using this library is different from other Node modules that I've tried.

I'm not really sure where the example code in the readme should go. Do I need to build the package before using it in my own index.js file or how is it meant to be implemented? Maybe a more detailed "getting started" section in the readme could help or maybe I just need to read more about the fundamentals of this setup in general. :)

**Comment by leolabs** [comment]
Hey @tobiasger,
No need to build the package, you can just install it with NPM or Yarn and then require it in your JS file.

I think if you use standard JS, you can do it like this:

```js
const { Ableton } = require("ableton-js");

const ableton = new Ableton();

const test = async () => {
  ableton.song.addListener("is_playing", p => console.log("Playing:", p));
  ableton.song.addListener("tempo", t => console.log("Tempo:", t));

  const cues = await ableton.get("cue_points");
  console.log(cues.map(c => c.raw));
};

test();
```

Let me know if this works for you :)

**Comment by tobiasger** [comment]
Sorry, I'm so dumb. 

I actually did this earlier but for some reason I was expecting that the `console.log` statements would throw something out directly, but I just realized that they are listening to playing and tempo. It's working as expected now, thanks!

One additional slightly off-topic question: would this API let me handle opening, saving and creating files or is this not possible?

**Comment by leolabs** [comment]
Awesome, I'm glad it's working for you now! :)

Unfortunately, Ableton doesn't provide this API (yet). I'm hoping that new features will be added in Live 11. As soon as I have access to the new API, I'll see what's new.
