### ISSUE TITLE
select Scene

### ISSUE THREAD

**Issue by sfxter** [leolabs/ableton-js#23]
Sorry for such a noob question, but I'm stuck for a while now and can not find an answer.

I am struggling to select a scene. Although I was able to get selected scene by using 
 ` let selectedScene = await ableton.song.view.get("selected_scene");`
I can't set selected_scene.

I tried these without any success:
```
  await ableton.song.view.set("selected_scene", 4724534408);
   await ableton.song.view.set("selected_scene", "4724534408");
   await ableton.song.view.set("selected_scene", { nsid: "4724534408" });
   await ableton.song.view.set("selected_scene", { "nsid": "4724534408" });
   await ableton.song.view.set("selected_scene", selectedScene)

```
the error that I get is `UnhandledPromiseRejectionWarning: Error: Python argument types in
    None.None(View, int)`

I also tried using sendCommand without success: 
```
let res = await ableton.sendCommand("song-view", null, "get_prop", {
    prop: "selected_scene",
  });
```

Any help would be appreciated.
Thank you in advance.

**Comment by leolabs** [comment]
Hey @sfxter! Sorry for the late answer. It seems this is an error in the library. Your first approach should be the one that works. I'm working on a fix and fill push it soon :)

**Comment by sfxter** [comment]
Hello, thank you for your reply. This gives me a lot of hope :)

**Comment by leolabs** [comment]
I've fixed the issue :)

Let me know if it works for you now.

**Comment by sfxter** [comment]
This works for me perfectly now with Node JS. Thank you so much!

**Comment by sfxter** [comment]
Although `await ableton.song.view.set("selected_scene", 4724534408)` command works, but I found one strange thing, that every time when I call command to get selected scene, or get all scenes, NSID and ID of these scenes are always changing.
Strangely, but setting selected scene with old NSID works correctly.
Unfortunatelly I can not use NSID for UI and have to use scene name instead.
Is this expected behavior, that these nsid keep changing with every call?

Also I noticed, that "set selected scene" selects a clip slot in a track, that was selected last, instead of selecting a scene clip itself (which is in Master track). Do you think it would be possible to solve or should I just use command to select master track after selecting scene?

Thank you for your time.

**Comment by leolabs** [comment]
The changing IDs is unfortunately not something I can do anything about. As a bit of context, Ableton's API doesn't provide any IDs themselves, so what I do is generate IDs and [store a map of ID->Object](https://github.com/leolabs/ableton-js/blob/master/midi-script/Interface.py#L5-L9) on the Python side of things so the objects can be accessed later. I can't, however, check whether two objects are the same as Ableton's API returns new instances on every request, so the IDs always change.

In regards to the behaviour of the `set_selected_scene`, I want to keep the API as close to Ableton's as possible. That means I would rather not add any functionality that changes the behaviour.

**Comment by sfxter** [comment]
Thank you for your answer.
Luckily, Ableton recognize scene even with an old ID, so I'll stick with that ant test it out more.

I solved the scene clip selection by adding 2 lines 
  ```
const masterTrack = await ableton.song.get("master_track");
ableton.song.view.set("selected_track", masterTrack.nsid);
```
