### ISSUE TITLE
AbletonJS and React

### ISSUE THREAD

**Issue by sfxter** [leolabs/ableton-js#24]
Hello once again, thank you for such a cool module.
Do you think it would be possible to use ableton-js with React?
I am trying to use your module, but I get this error:

`TypeError: dgram_1.default.createSocket is not a function`
at node_modules/ableton-js/index.js:101

my minimal code looks like this
```

import React, { useEffect, useState } from "react";
import "./App.css";
import { Ableton } from "ableton-js";

const ableton = new Ableton();

function App() {
  return <div className="App"></div>;
}

export default App;


```
should I keep trying or is it impossible to use AbletonJS with React?
Sorry once again for noob question and thank you in advance for your time.

**Comment by sfxter** [comment]
Nevermind my question, as I understood this is a module for Node JS, but not React.
I found a way to connect them by using socket.io library.
If someone will have same question, I would suggest look at this example 

https://github.com/socketio/socket.io/tree/master/examples/create-react-app-example

**Comment by leolabs** [comment]
Good idea! Yeah, I used Socket.IO in AbleSet as well and had a good experience with it :)
