### ISSUE TITLE
Get clip name

### ISSUE THREAD

**Issue by dir** [leolabs/ableton-js#33]
Hey! Firstly, amazing job on the library.

Secondly, I'm trying to get a clip name after having selected it like so:

```js
let clip_slots = await tracks['main'].get("clip_slots")

clip_slots.forEach(async (slot) => {
    if(slot.raw.is_playing === true) {
      let clip = await slot.get("clip"))
      console.log(clip)
    }
});
```

I can't seem to find a way in the transformers, etc, to get the name of a clip, any advice would be much appreciated.

**Comment by leolabs** [comment]
You could go with `const name = await clip.get("name");`, that should return the clip's name.

**Comment by dir** [comment]
Apologies for the late response, this works wonderfully. Thank you!
