### ISSUE TITLE
Export Audio?

### ISSUE THREAD

**Issue by davidthekesler** [leolabs/ableton-js#35]
Thanks so much for releasing this library. It's much appreciated! From looking at the source code, and from the API documentation (https://nsuspray.github.io/Live_API_Doc/11.0.0.xml) I haven't been able to track down the command to export a Song as audio. Any chance you've come across it?

**Comment by leolabs** [comment]
Hey @davidthekesler,

I don't think it is possible to export a Song as audio using the Python API, unfortunately.

Depending on what you want to do, you could try to emulate keypresses to open Live's export dialog. I think there are some packages on NPM that allow you to do this.

**Comment by davidthekesler** [comment]
Thanks! I really appreciate you taking the time to respond.
David Kesler
415-215-5758

**Comment by leolabs** [comment]
You're welcome :)
