### ISSUE TITLE
Get a list of clips in a track in the arrangement view

### ISSUE THREAD

**Issue by chozilla** [leolabs/ableton-js#37]
Hello,
I am having troubles finding documentation on the **arrangement view** and how to access and modify **clips** there.
I would like to write a script that synchronizes the midi data on clips in the timeline with a session view clip in a slot with the same clip name. 
_Currently I am not sure if anything like that can be done with the python api._

Thanks for the help and best regards
 \ chozilla

**Comment by leolabs** [comment]
Hey @chozilla,

Afaik, unfortunately it's not possible to manipulate clips in the arrangement view using Ableton's Python API :/

I hope that Ableton will expand their Python API in the future, but so far, there haven't been a lot of updates in the past years.

Best,
Leo
