### ISSUE TITLE
Reconnecting to Ableton fires unexpected events

### ISSUE THREAD

**Issue by zactopus** [leolabs/ableton-js#41]
When I disconnect and reconnect Ableton I get the following events:

+ Disconnect
+ Connect
+ Disconnect (unexpected)
+ Connect (unexpected)

I looked into the JS code further and it seem like it may be a bug in the Python `midi-script` or further up as this is what I see in the raw messages coming into the `handleIncoming`.

I am using:

+ Ableton Live 11 Intro
+ Macbook Pro (M1 Chip) - Monterey v12.2.1

**Comment by zactopus** [comment]
I'm happy to try and fix but my Python is rusty so opening a issue first incase this is just to do with my (shitty M1 chip/Monterey) setup.

**Comment by zactopus** [comment]
Just so you know @leolabs this ticket is for the library firing a disconnect and extra connect incorrectly, and wasn't fixed by the mentioned issue

**Comment by leolabs** [comment]
Oh, thanks for the heads-up! I misread the issue as something related to your PRs.

How did you trigger the disconnect and reconnect in Ableton? Did you do it by restarting the app or by loading a new project?

I'll try to reproduce this on my side then.

**Comment by leolabs** [comment]
Hey @zactopus, I've just released a major update to this library and can't reproduce the issue anymore. I'll mark this as fixed for now, but feel free to reopen it if you still encounter the issue :)
