### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KaelBaldwin** [leolabs/ableton-js#45]
Hello! Just came across this project and think this and AbleSet looks brilliant. Thank you for your hard work! 

Would you consider adding a license to this repo so it can be used? I'm interested in playing around with this some locally and maybe using in combo with GoLang and web-assembly or something. Might be able to lend a hand with the repo as well if you'd be receptive to that. Thanks!

**Comment by leolabs** [comment]
Thanks for the heads-up! I've added an MIT license file to the repo.

If you have ideas on how to improve the project, feel free to open new issues or PRs. I'm always open for them :)
