### ISSUE TITLE
Nothing but timeouts

### ISSUE THREAD

**Issue by jBernz** [leolabs/ableton-js#5]
Hi I've installed on OSX. I believe I've followed all the instructions, but whenever I call Ableton.song.get() I receive a timeout.

Here are the logs from Ableton:

`0-03-04T13:51:10.619049: info: Python: INFO:_Framework.ControlSurface:619 - LOG: (AbletonJS) Starting on: ('127.0.0.1', 9001), remote addr: ('127.0.0.1', 9000)
2020-03-04T13:51:10.619076: info: RemoteScriptMessage: (AbletonJS) Starting on: ('127.0.0.1', 9001), remote addr: ('127.0.0.1', 9000)
2020-03-04T13:51:10.619238: info: Python: INFO:_Framework.ControlSurface:619 - LOG: (AbletonJS) Socket Event connect(None): null
2020-03-04T13:51:10.619262: info: RemoteScriptMessage: (AbletonJS) Socket Event connect(None): null`

I don't see errors but 'connect(None): null seems a little weird. Any idea what is going on?

**Comment by jBernz** [comment]
so I see that the ports are different in the control script and in the node module. Does this need to be updated or did I miss something in your docs?

**Comment by leolabs** [comment]
Hey @jBernz,
one problem might be that port 9000, the one that ableton-js uses to send messages to Ableton, is already in use by another app. Just today I found out that Native Instruments uses the same ports, so I've updated them in the scripts. Could you try updating ableton-js and the midi script to the latest version and see if it works now? :)

**Comment by jBernz** [comment]
I updated the control script to use 9004 and 9005 and it now works! thank you for your response

**Comment by leolabs** [comment]
Perfect! Have fun with the library and feel free to open another issue if you have any other questions! :)
