### ISSUE TITLE
Numerus "Message could not be assigned to any request" Errors

### ISSUE THREAD

**Issue by thallosaurus** [leolabs/ableton-js#56]
Hello!

I'm currently writing an app which uses your module and I face a literal wall of errors from it.

I also don't understand where this errors come from.

You find all changes which include your library on [this commit](https://github.com/thallosaurus/homebrewdj/commit/a40b61c745fe736dd76d8523cce5cd1456f333e8?diff=unified#diff-e97152ee2c32d4ff1b5bc526c7b4943a3d7c0f10352f451fff0521ca68e0cd17)

I attached a log file from my program which contains the mentioned errors.
[errors.log](https://github.com/leolabs/ableton-js/files/9397476/errors.log)

**Comment by leolabs** [comment]
Hey @thallosaurus,

This error can occur if you add an event listener to something in Live and then restart your Node script without restarting Live. The Python script will still send updates for the old event listeners to the new instance of your Node script which leads to the errors you're seeing.

I understand this is a bit annoying so I've just pushed da32ca5924df0ffb20fab981e0e98bb606cbef4a, which prevents errors from being emitted for received events if there's no matching event listener.
