### ISSUE TITLE
get clips

### ISSUE THREAD

**Issue by jBernz** [leolabs/ableton-js#6]
hey so I'm looking for a way to listen to each scene in my set, the number of clips it has, and whether they are recording, stopped, playing, etc.

It doesn't seem like the library has any notion of clips as of yet though, correct?

**Comment by leolabs** [comment]
As of now, unfortunately, no. But it should be fairly easy to implement if you want to submit a PR. Take a look at the Scene class ([Python](https://github.com/leolabs/ableton-js/blob/master/midi-script/Scene.py), [JS](https://github.com/leolabs/ableton-js/blob/master/src/ns/scene.ts)) for example. The complete API has been documented by Julien Bayle [here](https://julienbayle.studio/PythonLiveAPI_documentation/Live10.1.xml), so you can get the available properties and methods.

If you don't want to do this, I could also do it in a few days.

**Comment by jBernz** [comment]
I'm pretty close to getting this working, but for some reason song.get('scenes') doesn't return scenes with an nsid. I've spent a while trying to figure that out - any idea why that might be?

**Comment by leolabs** [comment]
Could you show me the current state of your code? Then I'll take a look :)

**Comment by jBernz** [comment]
https://github.com/jBernz/ableton-js

**Comment by jBernz** [comment]
ah I was looking in the wrong place, I believe its working now

**Comment by leolabs** [comment]
Perfect! I couldn't find the problem either, your new code looks perfectly fine to me :)
I just noticed that you're working on an outdated version of the midi script. Maybe you could pull in the newest version (the one with an `Internal.py` file/ns) and build on top of that. If not, I'll see that I'll merge the two versions correctly when you create the PR.

**Comment by jBernz** [comment]
https://github.com/leolabs/ableton-js/pull/7

**Comment by leolabs** [comment]
I'll close this issue here as your changes have been merged :)
