### ISSUE TITLE
"create_midi_track() argument after ** must be a mapping, not list"

### ISSUE THREAD

**Issue by IngoOutgo** [leolabs/ableton-js#64]
I'm trying to create a new Midi Track using `ableton.song.createMidiTrack(1)`, however, I get the following error:

```
Error: create_midi_track() argument after ** must be a mapping, not list
    at Ableton.handleUncompressedMessage (D:\Desktop\musicgen-simple\node_modules\ableton-js\index.js:222:41)
    at Ableton.handleIncoming (D:\Desktop\musicgen-simple\node_modules\ableton-js\index.js:202:22)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage (node:dgram:930:8)
[ERROR] 15:10:28 Error: create_midi_track() argument after ** must be a mapping, not list
```

I'm using Windows and the Live 11 Beta (11.2.10b1)

EDIT: Also occurs when using Live 11 (not Beta)

**Comment by IngoOutgo** [comment]
The obvious workaround btw, is to simply send the command yourself, which is very easy!

```
s.sendCommand('create_midi_track', {index: 1})
```

This library is amazing, very well typed, and easy to work with!
I'll leave this open for now, since it seems to be a bug, but feel free to close, as I myself am happy with this workaround :)

**Comment by leolabs** [comment]
Thank you for the bug report! I've just released an update with a fix for it :)
