### ISSUE TITLE
How do I get the ID of an object?

### ISSUE THREAD

**Issue by IngoOutgo** [leolabs/ableton-js#65]
I have a clip that I would like to place in the Arrangement View.

"Track" has the function "duplicateClipToArrangement", which takes the ClipID as an argument.. But how do I actually get that ID?

**Comment by IngoOutgo** [comment]
For this too I was able to get a workaround, I might even open a PR later this week :)
I added the following to my Track.py of the MIDI Remote Script:
```
def duplicate_clip_to_arrangement_by_index(self, ns, clip_index, time):
    return ns.duplicate_clip_to_arrangement(ns.clip_slots[clip_index].clip, time)
```

Which then allowed me to duplicate using the index:

```
await ableTrack.sendCommand('duplicate_clip_to_arrangement_by_index', {
  clip_index: 0,
  time: 1234,
})
```

**Comment by devthane** [comment]
I think it is just clip.raw.id

**Comment by leolabs** [comment]
I've updated the function to accept a `Clip` object in addition to a raw clip ID to make this a bit easier to use.
